trigger: 'none'

pool: 'Default'

variables:
  configuration: 'Release'
  dotnet_version: '8.x'

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              packageType: 'sdk'
              version: $(dotnet_version)
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - task: DotNetCoreCLI@2
            displayName: 'Restore'
            inputs:
              command: 'restore'
              projects: '**/*.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'Build'
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '--configuration $(configuration)'

          - template: decrypt-file.yml
            parameters:
              input_file: './appsettings.secrets.json.enc'
              output_file: './appsettings.secrets.json'
              key: $(DECRYPTION_KEY)

  - stage: Publish
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Publish
        displayName: 'Publish'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Publish'
            inputs:
              command: 'publish'
              arguments: '--configuration $(configuration) --output $(Build.ArtifactStagingDirectory)/publish'
              projects: '**/*.csproj'
              publishWebProjects: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/publish'
              artifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploy
    dependsOn: Publish
    condition: succeeded()
    jobs:
      - job: DeployToAzure
        displayName: 'Deploy'
        steps:
          - task: AzureWebApp@1
            displayName: 'Deploy'
            inputs:
              azureSubscription: 'AzureServiceConnection'
              appType: 'webAppLinux'
              appName: 'dev-hancock'
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
              deploymentMethod: 'auto'