trigger:
- main

pool: 'Default'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Install'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'
  displayName: 'Restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration Release --no-restore --output $(Build.BinariesDirectory)/build'
    projects: '**/*.sln'
  displayName: 'Build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--configuration Release --no-build --output $(Build.BinariesDirectory)/build'
    projects: '**/*.sln'
  displayName: 'Test'